### ISSUE TITLE
Lag/UI freeze

### ISSUE THREAD

**Issue by rishabhbhatia** [xmuSistone/android-page-transition#2]
Hi i just copied the code from app folder & i am trying to run it on my device. It's super slow & sluggish. Basically the view pagers are not even sliding properly  & i constantly see The application may be doing too much work on its main thread on my android studio, something freezes up my main thread. I see these logs when i start to swipe. But when i download & install the apk u have put on my same device it works perfectly fine. Can you help, are there some changes you have  not pushed yet? Thanks

**Comment by xmuSistone** [comment]
Hello, I downloaded the newest code just now, and without any modification, android studio works fine for my phone device. So i cannot figure out what the key point to your problem is. 
You can try the newest code without any modification. If problem still exists, you should localize the root of the problem one step by one step.  First of all, maybe the CustPageTransformer causes the problem, then the Fragment's DragLayout, finally the transition part. Hope that help.

**Comment by rishabhbhatia** [comment]
Hi thanks. Your answer made me redo everything & finally it works as expected, no lags nothing. My problem was i made a very stupid decision to have my resources under drawable folder instead of drawable-xxhdpi which turned out to be the issue when i googled. The code worked perfectly, it was the resources which consumed so much memory of the main UI thread. So if it helps anyone don't put resource images under drawable instead of drawable-xxhdpi, it won't work as expected. Can you help with this. My app usage pattern as user is I open app, i start swiping cards to left, i swipe one up i see the details page, as soon as i am done i always swipe down twice before i realize that's not how i go back. Would you have time to help make something which helps go back using gestures & animations.

**Comment by xmuSistone** [comment]
Yet i haven't come across your issue of drawable and drawable-xxhdpi. 
And i m sorry that i haven't got your point of going back by using gestures and animations. Can you describe it with more details?

**Comment by rishabhbhatia** [comment]
Hi from main screen i drag from bottom-up to go to detail screen with transition. Can you help add something to library where user can drag from up-down on details screen & come back to the same home screen with transitions.

**Comment by xmuSistone** [comment]
@rishabhbhatia up-to-bottom can surely be implemented, it shares the same principle with bottom-to-up mode. In this repository, card could also be jumped by click event. In my opinion, click event makes it much more convenient to start the detail page transition.
If up-to-bottom is wanted, i need to see the designed animations. otherwise, i have no idea about how shared-elements gather together.

**Comment by rishabhbhatia** [comment]
Hi done, thanks. Loved your work +1
